version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: music
    environment:
      - ADVERTISE_IP=http://<localhost>:32400/ # La IP pública donde estará Plex
    ports:
      - "32401:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ./config:/config
      - ./data:/data
      - ./transcode:/transcode
      - ./music:/music
    restart: unless-stopped

